### PR TITLE
Added a link to the package in the openSUSE games repository

### PR DESCRIPTION
**Pull request by Mailaender**
I submitted an RPM package for @openSUSE https://build.opensuse.org/request/show/341772 which will be available to end users via https://software.opensuse.org/ once reviewed, accepted and the mirrors have synced.

### CODE REVIEW

**Comment by tehhowch** [comment]
Got a more pertinent link?

**Comment by Mailaender** [comment]
Yes, the one I added here: https://software.opensuse.org/package/endless-sky

**Comment by MCOfficer** [comment]
I assumed the build service was entirely automated; is there a reason this is still 0.9.8?

**Comment by Mailaender** [comment]
Latest version for Tumbleweed is 0.9.10 and while the builds are automated, updates are not.

**Comment by tehhowch** [comment]
(there are conflicts that prevent merging this)

**Comment by Mailaender** [comment]
It looks like you don't link Linux packages anymore. Plus you ignored my pull requests for 7 years...

**Pull request closed without merging**
