### PR TITLE
Add a plug-in list powered by EndlessSkyCommunity/endless-sky-plugins

### PR DESCRIPTION
**Pull request by MCOfficer**
This PR adds an html table with plug-ins to plugins.html. The data is dynamically fetched from [plugins.json](https://github.com/EndlessSkyCommunity/endless-sky-plugins/blob/master/generated/plugins.json). If javascript is disabled for some reason (this is 2020), the table just doesn't display.

Demo: https://mcofficer.github.io/endless-sky.github.io/plugins.html

### CODE REVIEW

**Comment by MCOfficer** [comment]
> Great first take, but passing remote data directly into strings that are treated as safe HTML is a huge XSS vulnerability.

The only thing that is being linked and could be changed behind our backs is the image URL. I'm not sure if that is in fact a vulnerability, in that case we could probably use duckduckgo's image proxy. All other data is curated in endless-sky-plugins, if that repo is compromised we are in deep shit either way.

> We should also be reporting the license(s) associated with each plugin.

+1, https://github.com/EndlessSkyCommunity/endless-sky-plugins/issues/19

**Comment by tehhowch** [comment]
Any HTML markup in any of these plugin fields will be used as-is, which is not ok. This table must not break because a plugin uses ASCII art for a description, etc. Properly creating this table also means we're robust to data source integrity, can use multiple data sources, and so on.

Currently one cannot use markup to format text consumed by Endless Sky, but that may change when the game offers non-ascii character support. Whatever markup is usable there could conceivably end up being passed to this table, too.

**Comment by MCOfficer** [comment]
> Any HTML markup in any of these plugin fields will be used as-is, which is not ok. This table must not break because a plugin uses ASCII art for a description, etc. Properly creating this table also means we're robust to data source integrity, can use multiple data sources, and so on.
> 
> Currently one cannot use markup to format text consumed by Endless Sky, but that may change when the game offers non-ascii character support. Whatever markup is usable there could conceivably end up being passed to this table, too.

It should not become relevant for the foreseeable future, but i'll look into it.

**Comment by MCOfficer** [comment]
Back to the drawing board until the index conforms to the [RFC](https://github.com/EndlessSkyCommunity/endless-sky/pull/53).

**Comment by tehhowch** [comment]
> Back to the drawing board until the index conforms to the [RFC](https://github.com/EndlessSkyCommunity/endless-sky/pull/53).

Didnt that RFC only cover how authors will submit their plugin data, not how the generated files will be formatted or served?

**Comment by MCOfficer** [comment]
Yes, but i will at least make a few minor changes, maybe more. I don't want this to be merged until then.

**Comment by MCOfficer** [comment]
Ready to review now.

All values are being properly escaped due the use WebAPIs rather than string concatenation; i failed to inject anything into the table  with a [faked plugin index](https://gist.github.com/MCOfficer/214545deb68a05ee35827b28d846b189), the worst thing i could do was straight up break it by writing invalid JSON. In that case the table just isn't displayed.

We now have the choice between using `description` or `shortDescription`. Additionally, we can also show the version, license and author names as separate columns.

**Pull request merged**
